### ISSUE TITLE
Multiple issues: Having to save the model immediately

### ISSUE THREAD

**Issue by thomaskonrad** [mike-goodwin/owasp-threat-dragon-desktop#104]
I just played around a bit with Threat Dragon, and I ran into multiple issues. I'd like to summarize these here.

1. **Having to save the model immediately**: When creating a new model, I need to save it immediately. I'd prefer being able to play around with it before saving anything. So "Create New" instead of "Save" would be better IMHO.
1.  **Exception thrown, but cannot copy it**: When I open a model, an exception `Uncaught Exception: Error: Command failed: 4294967295`. Also, I cannot copy the exception so that I could easily post it here. It says `System.Net.WebException: The remote server returned an error (500) Internal Server Error.`
1. **Blank screen after creating model**: When the model is saved, a blank screen with no interaction options appear. Took me a while to find out where to go from here.
1. **The fact that I have to edit the model to add a diagram**: That seems counter-intuitive to me. I'd put the diagrams into the edit view of the model, and only put metadata into the edit dialog.
1. **I cannot drag whole trust boundaries**: When I point at a trust boundary, the cursor indicates that I can drag and drop the whole boundary, but instead, a new point is added to the curve, which I then drag. I could not find out a way to move a whole trust boundary at once.
1. **The protocol isn't shown in the Data Flow**: There is no indicator which protocol is in use, or whether it's encrypted, although I can specify these properties.
1. **Data Flow arrows are misaligned**: The arrows seem to point towards the direct line between two objects, instead of the direction of the very last part of the curve. That makes it misaligned when it's curved.

I'm happy to provide more details in case anything is unclear.

**Comment by jgadsden** [comment]
Hello @thomaskonrad - thanks for the feedback, and these are all good points.
Point 3. is a known (and severe) bug that we are trying to fix ... any help on this would be great #79 
It would be good to split out your points into separate issues so that they can be dealt with one by one. I can do this if you like? Or you may want to do it? Happy either way

**Comment by thomaskonrad** [comment]
Feel free to split up this issue and close it!

**Comment by jgadsden** [comment]
Thanks @thomaskonrad I have split them up and kept this issue for the first point in your list.
This feedback is much appreciated; hope you find the tool useful even with these issues.

**Comment by jgadsden** [comment]
Hello @thomaskonrad - this latest commit has changed the behaviour reported in your first point
