### ISSUE TITLE
Uncaught Exception thrown on Windows

### ISSUE THREAD

**Issue by jgadsden** [mike-goodwin/owasp-threat-dragon-desktop#107]
@thomaskonrad reports:
Exception thrown, but cannot copy it: 
When I open a model, an exception `Uncaught Exception: Error: Command failed: 4294967295`. Also, I cannot copy the exception so that I could easily post it here. It says `System.Net.WebException: The remote server returned an error (500) Internal Server Error`

**Comment by jgadsden** [comment]
Hello @thomaskonrad - I have not been able to reproduce this yet. Can you provide a way of reproducing it? And also details on which platform would be great

**Comment by jgadsden** [comment]
Hello @thomaskonrad
This is a windows server 404 error, and so this must be when using the Windows desktop version of TD:
`System.Net.WebException: The remote server returned an error: (404) Not Found`

**Comment by thomaskonrad** [comment]
It was because of a `(500) Internal Server Error`, so probably the error is (was?) on the server side.

**Comment by jgadsden** [comment]
Thanks @thomaskonrad - was it the desktop or the web-app version of Threat Dragon?

**Comment by thomaskonrad** [comment]
It was the desktop version!

**Comment by jgadsden** [comment]
Cool, thanks. I have not been able to reproduce this myself, so if you can reproduce it or see it again and if you could list what steps you took, that would be great

**Comment by jgadsden** [comment]
This issue has been migrated to the OWASP organisation area:
https://github.com/OWASP/threat-dragon-desktop/issues/3
