### ISSUE TITLE
Undo feature doesn't work on OSX desktop version 1.1.0

### ISSUE THREAD

**Issue by tomjwalsh** [mike-goodwin/owasp-threat-dragon-desktop#119]
I'm not able to get the Undo feature to work on OSX desktop version 1.1.0 from the "Edit" menu or with command z (⌘ Z).

**Comment by jgadsden** [comment]
hello @tomjwalsh 
The undo feature is only for text fields in Threat Dragon, not the elements in the diagram. I have tested this on my Mac and it works as expected for project text fields including threat text fields, with both menu and shortcut.

Are you expecting Undo for the diagram elements? This is the subject of a feature enhancement in the core repo:
https://github.com/mike-goodwin/owasp-threat-dragon-core/issues/58

Are you OK with me closing this issue as a duplicate?
