### ISSUE TITLE
Please digitally sign the Threat Dragon installer binaries 

### ISSUE THREAD

**Issue by ahusmc** [mike-goodwin/owasp-threat-dragon-desktop#122]
Hello.

Please digitally sign the Threat Dragon installer binaries.

Thank you,

Alfredo Hickman

**Comment by jgadsden** [comment]
Hello @ahusmc - agreed that this is something that should be done. We are always looking for help for Threat Dragon so suggestions on how to do this and any code would be great

**Comment by ahusmc** [comment]
Suggestions on how to digitally sign the installer binaries and code suggestions? 

Please don't take this the wrong way, but digitally signing installer binaries is pretty standard and considered a security best practice. This is not something that you write up some code for and submit an MR. The developer and publisher of the installer obtains a legitimate code signing certificate and then signs the installer binary before publishing the file so that others can validate the legitimacy and integrity of the installer file, and so that you don't get security errors for security services such as macOS Gatekeeper or Windows Defender when installing the package. 

Here are some resources to help:

https://www.digicert.com/code-signing/

https://www.digicert.com/code-signing/support/

Respectfully,

Alfredo Hickman

**Comment by jgadsden** [comment]
Hello @ahusmc these are very good points. 

@mike-goodwin will be doing this as part of the autoupdate feature #101 and (if I understand correctly) this will be part of that feature.

I think this issue #122 can be closed as part of #101 if you agree?

**Comment by jgadsden** [comment]
We should generally follow: 
https://wiki.debian.org/Creating%20signed%20GitHub%20releases
which summarises this well. This is something that needs to be done for autoupdate, and is a good additional security measure for github releases.

**Comment by ahusmc** [comment]
Thank you @jgadsden and @mike-goodwin .
