### ISSUE TITLE
Mac Package Still at v0.1.26

### ISSUE THREAD

**Issue by ossie-git** [mike-goodwin/owasp-threat-dragon-desktop#132]
Hi,

The latest Mac package available for download from [here](https://github.com/mike-goodwin/owasp-threat-dragon-desktop/releases) is still v0.1.26. It looks like it wasn't updated like the other pages. Thanks

![Screen Shot 2020-04-09 at 4 59 46 PM](https://user-images.githubusercontent.com/25382296/78867076-dd47dc00-7a83-11ea-8171-20e348b0e250.png)

**Comment by jgadsden** [comment]
Hello @ossie-git - could you double check that you are using this .dmg file:
https://github.com/mike-goodwin/owasp-threat-dragon-desktop/releases/download/v1.1/OWASP-Threat-Dragon.dmg
When I install from this location I get the following 
<img width="1113" alt="Screenshot 2020-04-09 at 08 22 38" src="https://user-images.githubusercontent.com/29352392/78874665-a56d7400-7a44-11ea-836b-f2ea4ec023e2.png">

**Comment by ossie-git** [comment]
Oops. Looks like I had an older version installed as well and searching for threat dragon in Finder defaulted to that. Searching for OWASP Threat Dragon points to the new one. Thanks

**Comment by jgadsden** [comment]
Good to see that you have been using Threat Dragon for so long :-) Thanks for resolving this
