### ISSUE TITLE
Add icons to electron builder / installer

### ISSUE THREAD

**Issue by jgadsden** [mike-goodwin/owasp-threat-dragon-desktop#133]
The icon files `cupcakes.icns`, `cupcakes.ico` and `cupcakes1024x1024.png` should be moved to the `content/icons` directory. The icon locations updated for these paths and icons added to electron builder configuration in `package.json`.

**Comment by jgadsden** [comment]
@fajabird I am happy to do this, but did not want to tread on your toes if you are planning to do it?

**Comment by fajabird** [comment]
no, please go ahead - I have no other plans right now.

**Comment by jgadsden** [comment]
added in pull request #134
