### ISSUE TITLE
macOS keyboard shortcuts

### ISSUE THREAD

**Issue by jmiltner** [mike-goodwin/owasp-threat-dragon-desktop#150]
It may sound nit-picky, but not having standard keyboard shortcuts for closing window and application really stumps me every time I use the app...

The standard shortcut for closing a window on macOS in `cmd-W`, the standard shortcut for closing/terminating an application is `cmd-Q` - currently ThreatDragon uses `cmd-F4` to close a window and `cmd-W` to "exit" the application.
In addition, macOS adds a standard "Windows" menu to the menubar, containing a "Close Window" item with shortcut `cmd-W`, which conflicts with the "Exit" item in the File/application menu added by ThreatDragon code.

I would therefore suggest the following changes (as per the attached patch):

- change keyboard shortcut for "Close Model" menu item to 'CmdOrCtrl+W' when platform == darwin
- change title for "Exit" menu item to "Quit" when platform == darwin
- change keyboard shortcut for "Exit"/"Quit" menu item to 'CmdOrCtrl+Q' when platform == darwin

Thanks for considering.

[MenuItemChanges.patch.gz](https://github.com/mike-goodwin/owasp-threat-dragon-desktop/files/4999861/MenuItemChanges.patch.gz)

**Comment by jgadsden** [comment]
Thanks for this @jmiltner - you make a very good point. I can create a branch in the new OWASP repo:

https://github.com/OWASP/threat-dragon-desktop

as Mike's repo has been migrated to this OWASP organisation area.

**Comment by jgadsden** [comment]
Done : branch created at https://github.com/OWASP/threat-dragon-desktop/tree/macos-kb-shortcuts
pull request at https://github.com/OWASP/threat-dragon-desktop/pull/16

@jmiltner would you like to review the pull request?

**Comment by jgadsden** [comment]
Pull request merged in repo OWASP/threat-dragon-desktop#16. This will go in to the version 1.3 release scheduled for mid-August 2020
