### ISSUE TITLE
Report?

### ISSUE THREAD

**Issue by breezy2u** [mike-goodwin/owasp-threat-dragon-desktop#160]
I'm using the desktop version and I need to make a report based on my threat model. The directions say their should be a report button, but I don't see one. Can someone help?
![image](https://user-images.githubusercontent.com/30732489/92240076-a4b8fc80-ee81-11ea-9c61-f01cda90921d.png)

**Comment by jgadsden** [comment]
Hello @breezy2u , what you need to do is save your diagram (the right hand button of the seven diagram buttons) and then exit from the diagram (the second button of the seven diagram buttons, marked with a cross).
You will then be returned to the project overview page, on which there is a report button - and take it from there :-)
Hope this helps, Jon
(BTW, version 1.3 came out yesterday, https://github.com/OWASP/threat-dragon-desktop/releases/tag/v1.3 )

**Comment by breezy2u** [comment]
Ok. So I close it to make the report. Got it. Thank you!

**Comment by breezy2u** [comment]
Anything specifically special about the new version that I should upgrade
before the report?

**Comment by jgadsden** [comment]
You are welcome! Do you want to close the issue?
The new version is more stable, but the big difference is the beginnings of support for LINDDUN and CIA, alongside STRIDE. The report feature stays the same

**Comment by breezy2u** [comment]
sure

**Comment by breezy2u** [comment]
oh wait!

**Comment by breezy2u** [comment]
I closed the project but I still don't see a report button

**Comment by breezy2u** [comment]
nevermind. I'm a dummy. I found it.

**Comment by ypid** [comment]
> Do you want to close the issue?

Seems there is no way to close the issue via email. Can somebody close it :) ?

**Comment by jgadsden** [comment]
sure, I can close this ... done 👍
