### ISSUE TITLE
Blank storage on crash

### ISSUE THREAD

**Issue by gobrtg** [mike-goodwin/owasp-threat-dragon-desktop#167]
It seems that ThreatDragon nulls out a model when crashing. I had just made a model a couple of days ago, stored and everything looked fine. At some point when I wasn't at my computer the Dragon crashed leaving the json file completely blank.

Nearly blank that is:

{
  "summary": {
    "title": "New Threat Model"
  },
  "detail": {
    "contributors": [],
    "diagrams": []
  }
}

**Comment by jgadsden** [comment]
Hello @gobrtg - sorry to hear that TD crashed on you. What version were you running, and what operating system?

The json you list is the new and empty threat model that TD creates when needed, with a default file name of new-model.json. Did you save your threat model as a different file name?

**Comment by gobrtg** [comment]
Hey jgadsden, thanks for the quick response.
I had saved the file, and opened it again several times with no big issues. The version I'm running is 1.2.0 on Win10.

**Comment by jgadsden** [comment]
Hello @gobrtg - could you upgrade to version 1.3.1 ? I think there was an issue where there was a possibility that the model could be overwritten in version 1.2 and earlier ... but I can not remember which issue it was (I am getting old ;-) )

The updates can be found here:
https://github.com/OWASP/threat-dragon-desktop/releases

Sorry again to hear about the loss of your work, I know how aggravating it is

**Comment by gobrtg** [comment]
Ok, thanks a lot jgadsden. Yeah, not a good feeling when it sinks in. But, I'll give it another try. Even though it has some short comings, I like the ThreatDragons simplicity. So thanks to all of you guys laying down the hours to deliver this to the community, and keep up the good work. If all goes well and I'll continue to use the Dragon I'll post issues as I go along.
