### ISSUE TITLE
Possible to lose components from diagram editor pane

### ISSUE THREAD

**Issue by jgadsden** [mike-goodwin/owasp-threat-dragon-desktop#18]
If I open up a threat model and start editing it, then use the View->Reload function, I get the error message '[Error] path must be a string or a buffer' and the diagram title is stuck on 'Loading ...' with no components in the diagram editor pane. I am using version (0.1.26) direct from this repo on Trisquel linux.
This is not a big issue at all - it recovers and the error is noticable and avoidable ... but thought I should flag it.

**Comment by mike-goodwin** [comment]
Fixed in PR #62 (finally)
