### ISSUE TITLE
known vulnerable 

### ISSUE THREAD

**Issue by Wingless-Archangel** [mike-goodwin/owasp-threat-dragon-desktop#20]
not sure you are aware of it or not but it's good to upgrade your required dependency to the latest stable version

[Dependency-Check Report.pdf](https://github.com/mike-goodwin/owasp-threat-dragon-desktop/files/1348133/Dependency-Check.Report.pdf)

**Comment by mike-goodwin** [comment]
Thanks for the notification. I've had an enforced break from the project for a while but I'm back on it now and will adress this. 

FYI - I use [Snyk](https://snyk.io/) on the project. It does a similar job to Dependency Check, but it can also automagically make pull requests to update versions and do monkey patches in some cases too. Worth taking a look.

**Comment by mike-goodwin** [comment]
closed in pr #25 - no known vulns now :)
