### ISSUE TITLE
Add a Screenshot to the Readme

### ISSUE THREAD

**Issue by sroberts** [mike-goodwin/owasp-threat-dragon-desktop#23]
For GUI driven tools being able to "see it" makes a big difference in how to evaluate it. It would be really helpful to have that to look at from the screenshot, I'm not going to to download it just to see it. Thanks!

**Comment by timothydeblock** [comment]
There's a working prototype here https://threatdragon.org/login. The link is available on the readme page.

**Comment by mike-goodwin** [comment]
added some screenshots. the rationale for the desktop version is partly to support people who can't/won't give the prototype access to their GH. closed in pull request #25
