### ISSUE TITLE
Saved file contains just the string 'null'

### ISSUE THREAD

**Issue by richgmorg** [mike-goodwin/owasp-threat-dragon-desktop#24]
1.	Open Threat Dragon Desktop
2.	File | New model
3.	Add model title
4.	Save button
5.	Save “MyFile” (file is ok at this point)
6.	File | Close
7.	File | Save
8.     Open MyFile.json

Expected result
- File contains an empty model
- Opening the file shows an empty model

Actual result
- File contains just the string 'null'
- Opening the file spins indefinately

**Comment by mike-goodwin** [comment]
Hello Richard - thanks for the issue report.

When I reach step 7 File | Save the app asks me for a file location to save to - this is as expected.  Is tihs what you see? Are you selecting MyFile.json as the save location?

When you do File | Close the current model object is set to `null`, so if yo save it over your existing file, that would result in the file containing null. Have I reproduced it incorrectly?

**Comment by richgmorg** [comment]
Hi Mike, better late in replying than never!

Yes, at step 7  I saved the file on top  of itself.

**Comment by mike-goodwin** [comment]
This is fixed in the latest release v0.1.27
