### ISSUE TITLE
Copy/paste support

### ISSUE THREAD

**Issue by dehydr8** [mike-goodwin/owasp-threat-dragon-desktop#39]
The packaged electron application doesn't support copy/paste and other editing functions because the menu items and bindings need to be explicitly added. Reference: https://github.com/electron/electron/issues/2591

The menu items and bindings need to be added in `app/layout/shell.js` to enable support for the said functions.

**Comment by mike-goodwin** [comment]
As far as I can tell these editing functions do work via keyboard shortcuts (Ctrl-C etc.). Is this request to add a context (right-click) menu with the editing operations. I saw from your PR #40 that you were adding an edit submenu to the top menu bar. Which behaviour are you aiming for?

**Comment by dehydr8** [comment]
It works normally when we start the application using `npm run start` (triggers `electron .`) because it starts the app with electron's default menu items. But since we don't have these menu items in the packages application, Cmd+C and other keyboard shortcuts (on a mac) don't work.

**Comment by mike-goodwin** [comment]
So it fails on a Mac? OK, I should be getting a Mac to test on soon, as soon as I do I will get this addressed. Thanks for your contribution!

**Comment by mike-goodwin** [comment]
Merged in Pr #40
