### ISSUE TITLE
Crash When Using Trust Boundary

### ISSUE THREAD

**Issue by zachChilders** [mike-goodwin/owasp-threat-dragon-desktop#70]
Trust boundaries seem to crash the application when you go to change their shape.  Unfortunately, it's very difficult to move a threat boundary without accidently changing its shape dramatically.  As such, at least in my version, trust boundaries are unusable.

Version: 1.27.0 alpha
System: Windows 10
Repro:
- Add trust boundary to diagram
- Attempt to drag it from initial placement location
- The curve will try to recalculate itself and crash.

Any way I can submit logs?  Willing to go digging if I have some direction.

**Comment by jgadsden** [comment]
Agreed that I see the same issue running on a Macbook :
Desktop Threat Dragon version 0.1.26
Mac OS version 10.13.3 High Sierra
Weirdly I have tried it on a Windows 10 machine and I do not see this issue :
Desktop Threat Dragon version 0.1.26
Windows version : Windows 10 Home version 1607

**Comment by jgadsden** [comment]
Using the latest code from master, I still have this problem.
Desktop Threat Dragon : **master**
Mac OS version 10.13.3 High Sierra

**Comment by jgadsden** [comment]
This does not happen when using Threat Dragon version 0.6.3 on Debian Linux (Trisquel), so it seems to be MacOS specific

**Comment by jgadsden** [comment]
Note that there is an existing workaround for this issue, which is to zoom out until the trust boundary or data flow does not require scrolling.

**Comment by dk1010101** [comment]
I see this too but i don't get a crash. When i add a trust boundary and try to change the shape the canvas just goes blank. I can see the menus and they are clickable but unusable. Zooming doesn't do anything.

I am using 0.1.27 on Win10 Enterprise 1809.

**Comment by jgadsden** [comment]
Hello @dk1010101 - there is a fix for this as a pull request, but it has not been merged yet. There are some release images here that may help you, but only for Linux and MacOS OSX:
https://github.com/jgadsden/owasp-threat-dragon-desktop/releases
I can create one for Windows, will try and do it soon.

**Comment by jgadsden** [comment]
Should now be fixed in https://github.com/mike-goodwin/owasp-threat-dragon-core/pull/49
