### ISSUE TITLE
'Report' button does not exist

### ISSUE THREAD

**Issue by kingazf** [mike-goodwin/owasp-threat-dragon-desktop#71]
... or I am very obtuse and cannot find it. Tried with both my own threat model as well as the demo one. Any tips? 

Using the desktop version.

**Comment by jgadsden** [comment]
What version are you using @kingazf ? As far as I know this not yet available in the packaged downloads, and you have to checkout master branch and run from there using 'npm run start'

**Comment by k1kkan** [comment]
Same issue with macOS desktop application. To my understanding running npm `npm install` and `npm start` would require homebrew for macOS which is not an alternative for me.

**Comment by k1kkan** [comment]
Fixed by installing node.js from  https://nodejs.org/en/download/ and then install npm and run.

**Comment by jgadsden** [comment]
This will be fixed in the next release of TD desktop, which should be out by the end of Feb '20

**Comment by jgadsden** [comment]
Hello @kingazf and @k1kkan - the report button feature is now stable, and you should not get any more problems, with version 1.0 release:
https://github.com/mike-goodwin/owasp-threat-dragon-desktop/releases/tag/v1.0
