### ISSUE TITLE
Can't save on Mac after adding threat

### ISSUE THREAD

**Issue by coillarach** [mike-goodwin/owasp-threat-dragon-desktop#73]
Saving seems to work fine when the diagram only consists of dataflow objects. As soon as a threat is added, none of the save options work. The menu option displays a save file dialog even though the json file already exists and overwriting it removes the contents leaving just a JSON null. Using the button in the toolbar displays an on-screen error message which says "Cannot read property 'detail' of null". Removing the threat again does not get rid of the problem.
I am using the Desktop version 0.1.26 on MacOS 10.14.6

**Comment by jgadsden** [comment]
I do not have this problem when running TD v0.1.26 on MacOS 10.15. @coillarach could you try opening the sample model and seeing if you get the same problem? Just trying to rule out any problem with filesystem write permissions.
BTW I agree that v01.26 is the latest MacOS release, but it is very old at May 2017. I run the later versions of TD by cloning/ downloading the repo and then 'npm run install' followed by 'npm run start'

**Comment by lmcthbe** [comment]
I have similar issues on 10.15 after cloning the repo, the selected element are not showed and when it does, when a threat is added, none of the save options works.

**Comment by jgadsden** [comment]
@lmcthbe could you detail the steps that you take to reproduce this problem on MacOS 10.15 and cloning the latest TD ? I suspect that I do not see it because I am doing something different that you each time. Or is it because there is an error when running `npm install`?

**Comment by lmcthbe** [comment]
@jgadsden After fixing the gyp error when doing 'npm install' it helps TD to work better and element can be added to the diagram. 
About the save button, I have done extra testing and I found that I can get the save button not gray out just by clicking outside of the element that I have moved, it looks that the save button does not appears (after moving an element) when a another element or the background is not selected/clicked

**Comment by jgadsden** [comment]
Thanks for the info @lmcthbe - I can reproduce this issue from your instructions. It seems the Electron pull-down 'Save' always works even if the diagram save button is still greyed out.  I think this can be corrected in the owasp-threat-dragon-core source code. I can add an enhancement request in that repo.

**Comment by lmcthbe** [comment]
Great.

**Comment by jgadsden** [comment]
Hello @coillarach - the new version 1.0 of TD desktop is released:
https://github.com/mike-goodwin/owasp-threat-dragon-desktop/releases/tag/v1.0
and you should not have this issue any more.
Thanks for your help @lmcthbe
