### ISSUE TITLE
Export as PDF in Desktop App

### ISSUE THREAD

**Issue by p-** [mike-goodwin/owasp-threat-dragon-desktop#75]
Hi there,
nice project!
I saw that PR #100 adds reporting/PDF functionality to the Web app. It would be nice if the Desktop app also had that functionality.

**Comment by jgadsden** [comment]
Hello @p- could you tell me what platform you are running on? Is it MacOS? The PDF report is in the master branch but the MacOS .dmg file does not have these latest additions. If you run from a checkout of threat dragon then you should be able to open the report and export as PDF.
If you download (or clone) and then run `npm install` and `npm run start` you should see the report button.
I am not sure when new release images for MacOS (and also Windows and Linux) are planned, so this is a work-around for now

**Comment by p-** [comment]
Hi @jgadsden 
Ah I see it now, thanks!
(Searched the 'export function' only in the application menu).
