### ISSUE TITLE
Create releases for linux distros

### ISSUE THREAD

**Issue by jgadsden** [mike-goodwin/owasp-threat-dragon-desktop#78]
It would be good to have new set of release files for Windows and MacOS, as well as the linux distributions such as Debian and Fedora.

**Comment by cafl** [comment]
I am interested in being a tester of your Linux installer.  I have used the msft tmt for years and am tired of building out templates in a proprietary tool that doesn't match the environment I am modeling.  I want to use a tool that runs on Linux, so I would like to help make that happen.

**Comment by jgadsden** [comment]
Hello @cafl - we have not yet released the distros to this main repo, but I have put them on my fork for now:
https://github.com/jgadsden/owasp-threat-dragon-desktop/releases
Hope this helps

**Comment by jgadsden** [comment]
Hello @cafl this PR #77 has npw been marged to master, so if you would like to test it out that would be great

**Comment by cafl** [comment]
Will do.  Many commitments, so I probably will get to this late next week.

**Comment by jgadsden** [comment]
Thanks @cafl 
I am merging in some bug fixes this weekend, and then will produce a new release for the platforms that we can all test - most likely .exe, .deb and .dmg . If you are able to test .rpm then that would be great ... I do not have a RH / Fedora box or VM to hand. 
Leaving .snap alone for the moment, as I have not used these packages before.
Hope to get to a 1.0 release by Monday, fingers crossed.
Cheers, Jon

**Comment by jgadsden** [comment]
Hello @cafl - release is here, see what you can make of it :-)  : 
https://github.com/mike-goodwin/owasp-threat-dragon-desktop/releases/tag/v1.0
In the meantime I can now close this issue
