### ISSUE TITLE
Report in blank (desktop versión installed locally on Mac)

### ISSUE THREAD

**Issue by alexpeju** [mike-goodwin/owasp-threat-dragon-desktop#81]
Hi Mike,
I have the desktop version installed locally on my mac and for a few days when I want to see the model report, it shows me the blank summary, I can't find a way to see what's wrong.
When loading the project I get an error "Could not call remote function 'setFeedURL', check that the function signature is correct. Underlying error: could not get code signature for running application" 
I can add threats, flows and anything but when entering by the reports option I get the following error message "[Error] Cannot read property" cells "of undefined." for each diagram included in the model.
Do you know what may be happening?
I can share the model in case you have any idea what may be happening.

**Comment by jgadsden** [comment]
Hello @alexpeju 
It works OK for me when running on MacOS 10.15 Catalina, so this may be a permissions or installation issue. Could you advise what Macbook and what MacOS you are running on? Agreed that it would be good if you would like to share your threat model json file.
Can you check that you are running the latest version? Either clone this repo and then invoke `npm run install` and then `npm run start`, or you can use the beta version dmg file from https://github.com/jgadsden/owasp-threat-dragon-desktop/releases/download/v0.1.27-beta/threatdragon_0.6.3_osx_x64.dmg
-

**Comment by jgadsden** [comment]
Will retest this when the new version of TD desktop is released

**Comment by jgadsden** [comment]
Hello @alexpeju - can you now use the latest version of TD desktop? It has been released here:
https://github.com/mike-goodwin/owasp-threat-dragon-desktop/releases/tag/v1.0
and as far as I can tell it behaves correctly now
