### ISSUE TITLE
Console error messages displayed

### ISSUE THREAD

**Issue by jgadsden** [mike-goodwin/owasp-threat-dragon-desktop#97]
We get some console error messages when TD starts up. It is annoying and worrying for the user when these are briefly visible in the main application window. We need to either:
* fix the error + warning messages
or
* stop them appearing on the main window

**Comment by jgadsden** [comment]
Thanks @derekhillhp for reporting this

**Comment by derekhillhp** [comment]
After some trial and error, I was able to capture a screen shot of the startup messages. 
<img width="442" alt="Screenshot 2020-03-01 06 54 55" src="https://user-images.githubusercontent.com/5630875/75627957-aed40880-5b89-11ea-94a4-e2cb7fabe661.png">

**Comment by jgadsden** [comment]
The error messages are due to auto-update not working correctly, subject of PR #102 . Once this is merged in then these error messages are no longer displayed.
