### ISSUE TITLE
Java Script error

### ISSUE THREAD

**Issue by dschadt** [mike-goodwin/owasp-threat-dragon-desktop#98]
I have 2 W10 64bit installations, actual version/patchlevel.
On both machines a window appears with error message when using TD 1.0.0
there is no C&P or change of window size :-(

<img width="418" alt="2020-03-01 17_02_31-Error_top" src="https://user-images.githubusercontent.com/30535695/75629026-dacda900-5bde-11ea-9b6a-96b4df0d5285.png">

<img width="418" alt="2020-03-01 17_03_33-Error_bottom" src="https://user-images.githubusercontent.com/30535695/75629029-ddc89980-5bde-11ea-8e5a-5e6cb31c509c.png">

**Comment by jgadsden** [comment]
Hello @dschadt , is this using the released desktop version 1.0  .exe installer? Or from a git clone and `npm install` ? Certainly looks bad, and I assume the desktop application does not run after these errrors?

**Comment by dschadt** [comment]
yes and error appears after some time after starting TD ~ 2mins. Seems to be independent on any action within TD. Then Menus disappear as long as error is displayed. After confirming the message box menus are back and you can continue working. Error message seems to appear only once.
 Update request ?

**Comment by jgadsden** [comment]
Ah, this is different to my Windows 10 box, whoch does not see these errors. It could be something to do with a difference in the environment, but I am really not sure at all. Are you able to investigate and find a solution?

**Comment by dschadt** [comment]
probably main difference is a German W10 environment. Tried a VM installation with barely nothing installed (MSFT Office 2013/2019 & MSFT TMT 7.x), same error.

I'll attach the squirrelSetup log


[SquirrelSetup.log](https://github.com/mike-goodwin/owasp-threat-dragon-desktop/files/4273920/SquirrelSetup.log)

**Comment by jgadsden** [comment]
OK, thanks @dschadt for the log file, and it looks as though squirrel is complaining about not being able to access update at:
https://threatdragondownloads.azurewebsites.net/update/win32/1.0.0/releases
I have to admit to knowing next to nothing about Windows systems (I am a linux sort of person), and I know that we have not uploaded any files to MS Azure. I guess after 2 minutes or so squirrel gives up trying to find this update
Possibly we have enabled updates in the TD package configuration? I will see what I can find, but if you have any ideas that would be great

**Comment by dschadt** [comment]
looks like some default settings from squirrel

**Comment by jgadsden** [comment]
Hello @dschadt - found that this path is defined in app/config.autoupdate.js .

It seems best that we disable auto-updates for all platforms : Windows, MacOS and Linux.
I can do this, and the updates can be enabled again when they are working for all three platform flavours.

**Comment by jgadsden** [comment]
The js error is due to auto-update not working correctly, subject of PR #102 . Once this is merged in then this error dialog box is no longer displayed.
